.github/scripts/maybe-publish.sh
.github/workflows/node.yml

The script `.github/scripts/maybe-publish.sh` checks the version specified in the `package.json` against the versions in the NPM registry.
The grep command returned a result for `1.0.0` because the registry had a version `1.0.0-rc1`:
Turning the grep command into a regular expression solves the problem, but this requires to remove the output capture with `$()` (which removes newlines).

Node packages not published

---

sources/sdk/k8s-operator/.eslintrc

It isn't incorrect to have your exceptions alongside the module that use them.

👕 disable max-class-per-file rule

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/graphql/type-defs/annotation.graphql

The provided `Annotation` type in the GraphQL type definitions of the SDK was the only one without a corresponding input.
**NB:** in a later versions, validators for labels and annotations will be provided. They have the same structure but not the same syntax. The validators will be added as a GraphQL directive.

Add AnnotationField in sdk-k8s-operator GraphQL utilities.

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/web-service.js

Since the `createTerminus` method has been mocked, it failed the unit tests.
**NB:** E2E (End-To-End) tests are not yet automated.

🐛 Wrong type in SDK Kubernetes Operator

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/kube-interface.js
sources/sdk/k8s-operator/src/operator.js

The `kubernetes-client` dependency (the high level API) relies on the last LTS of `@kubernetes/client-node` (the low level API).
This version requires the `KubeConfig` class to be initialized at least with an empty configuration.
On a second note, the service account tied to the token used for authentication in the `ApolloServer` is unlikely to have the access permissions to CRDs API endpoints. It is also redundant to try to create the CRDs on each requests AND at startup.

🐛 Fix KubeConfig creation and CRD double-creation

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/kube-interface.js
sources/sdk/k8s-operator/src/resource-watcher.js

When the operator starts, it receives the complete history of the watched resources.
The events are `ADDED`, `MODIFIED` and `DELETED`. **They are not lowercase.**
Finally, the Kubernetes client backend expect lowercase HTTP headers, but the `-` is not replaced/transformed.
Silly mistakes, but we're getting closer to a stable release.

🐛 Fix Kubernetes interface

---

.github/dependabot.yml

This will enable the Dependabot dependency graph in the Insight tab.

👷‍♀️ add Dependabot configuration

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/yarn.lock

The previous version of `kubernetes/client-node` used `through` as dependency to create the stream objects for the `watch` endpoint.
We used this dependency as well in our mocks to emulate the Kubernetes client.
This PR reintroduces the dependency in `devDependencies` to fix the test suite.

✅ Add missing mock dependency

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/operator.js
sources/sdk/k8s-operator/tests/operator.spec.js
sources/sdk/k8s-operator/yarn.lock

When a token is sent via the `Authorization` HTTP header to the Apollo Server, it is used to authenticate the requests made to the Kubernetes API Server.
In order to avoid needlessly sending the token on each request, an HTTP-Only cookie should be sent back in the response whenever a token is received in the `Authorization` header.
When no token is found in the `Authorization` header, the Apollo Server should check for the cookie's presence.

✨ Add support for authentication via HTTP Only cookie

---

.github/workflows/node.yml

We are using NodeJS 14.X (LTS).
The CI pipeline was still using the old 12.X version branch.

👷‍♂️ ⬆ Upgrade NodeJS

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/kube-interface.js
sources/sdk/k8s-operator/tests/kube-interface/index.spec.js
sources/sdk/k8s-operator/tests/mocks/kubernetes-client.js

In the Kubernetes client, the `watch` endpoint for Custom Resources exists only if the client method `addCustomResourceDefinition()` has been called.
Therefore, the `KubeInterface` should request all the CRDs known by the Kubernetes API Server to initialize the client correctly.
**When will this PR be ready?**

🔨 Load all CRDs present in Kubernetes cluster

---

sources/sdk/k8s-operator/src/kube-interface.js

The methd `client.addCustomResourceDefinion` is used in a map, but its `this` argument was undefined.

🐛 KubeInterface client's method not binded

---

sources/sdk/k8s-operator/src/kube-interface.js
sources/sdk/k8s-operator/tests/kube-interface/watch.js
sources/sdk/k8s-operator/tests/mocks/kubernetes-client.js

The `getEndpoint` function was mutating a local variable.
Instead, the final value is reduced from a list of functions.

🔨 Simplify KubeInterface source code

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/operator.js

This PR aims to fix any requests to /graphql/logout (delete authentication httpOnly cookies) and add minor version

🔖🐛 Fix route /graphql/logout and upgrade to 1.4.1

---

sources/sdk/k8s-operator/src/kube-interface-utils.js
sources/sdk/k8s-operator/src/kube-interface.js

See [Kubernetes Authorization Overview](https://kubernetes.io/docs/reference/access-authn-authz/authorization/) for more informations.
This PR adds methods to the `KubeInterface` class, allowing the user to query the Kubernetes API Server for its authorizations.
**When will this PR be ready?**

✨ KubeInterface access review

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/src/graphql/utils/collection.js

This PR provides sane defaults for `paging` and `sorting` within the `collection` helper, preventing an error when they are not supplied.

🔖🐛 Fix GraphQL collection helper (v1.5.1)

---

sources/sdk/k8s-operator/src/kube-interface.js
sources/sdk/k8s-operator/tests/kube-interface/index.spec.js
sources/sdk/k8s-operator/tests/kube-interface/patch.js

This PR introduces the following changes:

✨ Add possibility to override patch type

---

sources/sdk/k8s-operator/src/errors.js
sources/sdk/k8s-operator/src/operator.js
sources/sdk/k8s-operator/src/server-factory.js
sources/sdk/k8s-operator/tests/server-factory.spec.js

This PR introduce the following changes:

✨ Make HTTP server optional

---

sources/sdk/k8s-operator/src/kube-interface.js
sources/sdk/k8s-operator/tests/kube-interface/index.spec.js
sources/sdk/k8s-operator/tests/kube-interface/replace.js
sources/sdk/k8s-operator/tests/mocks/kubernetes-client.js

This PR provides the following changes:

✨ Add replace method to KubeInterface

---

sources/sdk/k8s-operator/package.json
sources/sdk/k8s-operator/yarn.lock

This PR reverts datapio/opencore#242.
See issue kubernetes-client/javascript#632 for more informations.

⏪ Rollback @kubernetes/client-node from 0.14.2 to 0.14.0

---

apps/datapio_play/lib/datapio_play/dsl.ex
apps/datapio_play/lib/datapio_play/manifest.ex
apps/datapio_play/lib/datapio_play/step_logger.ex
apps/datapio_play/lib/datapio_play/step_logger_collectable.ex
apps/datapio_play/lib/datapio_play/utils.ex

This PR provides the following changes:

💄 Improve logging
